# Generated by Django 5.1.7 on 2025-05-07 14:44

import django.db.models.deletion
import perfil.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='neon_color',
            field=models.CharField(default='#00ffcc', max_length=20),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pics/', validators=[perfil.forms.validar_tamano_imagen])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.userprofile')),
            ],
        ),
    ]
