# Generated by Django 5.2 on 2025-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_userprofile_total_score_userprofile_total_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
