# Generated by Django 5.2 on 2025-05-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_userprofile_active_skin_userprofile_owned_skins'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de logros obtenidos'),
        ),
    ]
