# Generated by Django 5.2 on 2025-05-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_userprofile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='puntos',
            field=models.PositiveIntegerField(default=0, help_text='Puntos acumulados por el usuario'),
        ),
    ]
