# Generated by Django 5.2 on 2025-05-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='skins/icons/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
