# Generated by Django 5.1.6 on 2025-03-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioRegistro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'default_manager_name': 'objects'},
        ),
    ]
