# Generated by Django 5.1.6 on 2025-03-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioRegistro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
