# Generated by Django 5.1.7 on 2025-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioRegistro', '0002_alter_registro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='neon_color',
            field=models.CharField(default='#00ffcc', max_length=7),
        ),
    ]
