# Generated by Django 5.1.6 on 2025-03-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioRegistro', '0002_registro_is_verified_registro_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='registro',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
