# Generated by Django 5.1.6 on 2025-03-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioRegistro', '0003_remove_registro_fecha_alter_registro_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='verification_token',
        ),
    ]
