# Generated by Django 5.1.6 on 2025-10-07 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_create_word_levels_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_seed', models.CharField(blank=True, default='', max_length=64)),
                ('total_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], default='CREATED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('lang', models.CharField(default='es', max_length=8)),
                ('accepted', models.BooleanField(default=False)),
                ('delta', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='game.game')),
            ],
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'created_at'], name='game_game_status_9bfe99_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player'], name='game_game_player__b7b992_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['game', 'word'], name='game_submis_game_id_095fe9_idx'),
        ),
    ]
