# Generated by Django 5.1.6 on 2025-10-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_submission_game_game_game_status_9bfe99_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted', True)), fields=('game', 'word'), name='uniq_word_per_game_accepted'),
        ),
    ]
