# Generated by Django 5.2 on 2025-04-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_category_options_word_is_validated_and_more'),
        ('game', '0004_word_is_validated_alter_word_categories_and_more'),
    ]

    operations = [
    ]
